# Declaring scalars, vectors, and matrices <hr style="border:2px solid #108999"> </hr>

### Import the relevant libraries

In [1]:
import numpy as np

### Scalars

In [2]:
s =5 
s

5

### Vectors

In [4]:
v = np.array([5, -2, 4])
v

array([ 5, -2,  4])

### Matrices

In [5]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [6]:
type(s)

int

In [7]:
type(v)

numpy.ndarray

In [8]:
type(m)

numpy.ndarray

In [10]:
s_array = np.array([5])
type(s_array)

numpy.ndarray

### Data Shapes

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

In [13]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [14]:
s_array.shape

(1,)

# Creating tensor <hr style="border:2px solid #108999"> </hr>

In [15]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [16]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [17]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [18]:
t.shape

(2, 2, 3)

### Manually creating a tensor

In [19]:
t_manual = np.array([[[5,12,6], [-3,0,14]], [[9,8,7], [1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [20]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [21]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

# Adding vector together <hr style="border:2px solid #108999"> </hr>

In [23]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [24]:
v1+v2

array([ 2,  4,  6,  8, 10])

In [25]:
v1-v2

array([0, 0, 0, 0, 0])

# Transpose <hr style="border:2px solid #108999"> </hr>

In [3]:
import numpy as np
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [5]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [6]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [7]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [8]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

### Transposing Scalars

In [9]:
s = np.array([5])

In [10]:
s.T

array([5])

### Transposing Vectors

In [11]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [12]:
x.T

array([1, 2, 3])

In [13]:
x.shape

(3,)

In [14]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [15]:
x_reshaped.T

array([[1],
       [2],
       [3]])

# Dot Product of Vectors <hr style="border:2px solid #108999"> </hr>

### Vector x Vector

In [16]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [17]:
np.dot(x,y)

-66

In [18]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

np.dot(u,v)

18

### Scalar x Scalar

In [19]:
np.dot(5,6)

30

In [20]:
np.dot(10,-2)

-20

### Scalar x Vector

In [21]:
x

array([ 2,  8, -4])

In [22]:
5*x

array([ 10,  40, -20])

# Dot Product of Matrices <hr style="border:2px solid #108999"> </hr>

### Scalar x Vector

In [25]:
5*x

array([ 10,  40, -20])

### Sclar x Matrix

In [26]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix x Matrix

In [28]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [29]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

In [30]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [31]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [32]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])