# Introduction to NumPy

## Installing & Updating the Package

NumPy comes pre-isntalled if you're using Anaconda. 
**pip install numpy** 

To get the latest version:
**pip install numpy --upgrade**

### Importing NumPy

In [1]:
import numpy as np

### Using NumPy

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

### NumPy Documentation

https://numpy.org/devdocs/ <- <i> A link to the NumPy documentation

In [5]:
np.mean(array_b, axis=0)

array([2.5, 3.5, 4.5])

### Exercise:

In [7]:
#np.array() funn to create an array variable [4,5,7,10]

array_hw_1 = np.array([4,5,7,10])
array_hw_1

array([ 4,  5,  7, 10])

In [8]:
#np.array() funn to create a 2x2 array with the same values

array_hw_2 = np.array([[4,5],[7,10]])
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

In [11]:
#np.mean() funn on each array

np.mean(array_hw_1), np.mean(array_hw_2)

(6.5, 6.5)

In [14]:
#find the mean for all the rows of array_hw_2

np.mean(array_hw_2, axis=1)

array([4.5, 8.5])

## [4     5]
## [7     10]

In [15]:
#find the mean for all the col of array_hw_2

np.mean(array_hw_2, axis=0)

array([5.5, 7.5])

In [17]:
import numpy as np
np.mean(array_hw_2, axis=0, dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations