In [1]:
import numpy as np

# create array using numpy
arr1d = np.array([1,2,3,4])
arr1d

array([1, 2, 3, 4])

In [3]:
print(type(arr1d))
print(arr1d.shape)

<class 'numpy.ndarray'>
(4,)


In [5]:
arr2d = np.array([1,2,3,4])
arr2d.reshape(2,2)    #2 row, 2 col

array([[1, 2],
       [3, 4]])

In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [8]:
##2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
arr2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [10]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)    #Output: (2,3)
print("No. of dimensions:", arr.ndim)   #Dimension: 2
print("Size No. of the elements:", arr.size) #Size: 6
print("Data type:", arr.dtype) #Data type: int64
print("Item size (in bytes):", arr.itemsize)  #Output: 8

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
No. of dimensions: 2
Size No. of the elements: 6
Data type: int64
Item size (in bytes): 8


In [25]:
##Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [27]:
#Universal Function:

arr=np.array([1,2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
#array slicing & indexing

arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
arr[0][0]

1

In [35]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [45]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [46]:
arr[0][0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [49]:
#Statistical Concept - Normalization
## to have a mean of 0 & SD of 1

data=np.array([1,2,3,4,5])
mean=np.mean(data)
std=np.std(data)

normalized_data = (data-mean)/std
print("Normalized Data: ", normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [50]:
#Statistical Concept - Mean, Median, Mode, Std, Variance

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Mode: ", np.argmax(np.bincount(arr)))
print("Std: ", np.std(arr))
print("Variance: ", np.var(arr))

Mean:  5.5
Median:  5.5
Mode:  1
Std:  2.8722813232690143
Variance:  8.25


In [60]:
#Logical operation:

arr = np.arange(1,10)
arr[(arr>5) & (arr<8)]

array([6, 7])

In [61]:
arr[(arr>5) | (arr<8)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])