In [1]:
import numpy as np
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.empty((2,2))             #empty matrix

array([[2.12199579e-314, 1.16073170e-311],
       [6.00783825e-321, 1.16073170e-311]])

In [ ]:
np.eye(3)                   #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [16]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
np.random.random((2,2))

array([[0.71299316, 0.75219904],
       [0.71365535, 0.8350086 ]])

In [18]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [21]:
len(arr)

3

In [22]:
arr.ndim

2

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int32')

In [25]:
arr.dtype.name

'int32'

In [27]:
arr.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [32]:
arr = np.arange(1,11)
print(arr.reshape(5,2))
arr

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

print("Add:\n", arr1+arr2)
print("Sub:\n", arr1-arr2)
print("Mul:\n", arr1*arr2)
print("Div:\n", arr1/arr2)

Add:
 [[ 2  4  6]
 [ 8 10 12]]
Sub:
 [[0 0 0]
 [0 0 0]]
Mul:
 [[ 1  4  9]
 [16 25 36]]
Div:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
arr1d = np.arange(1,11)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.exp(arr1d)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [41]:
np.square(arr1d)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [43]:
np.sqrt(arr1d)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [44]:
np.log(arr1d)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [45]:
arr1.dot(arr2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [47]:
arr1 == arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [48]:
arr1<2

array([[ True, False, False],
       [False, False, False]])

In [49]:
np.array_equal(a,b)

NameError: name 'a' is not defined

In [50]:
# Agrregate function:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[9,8,7], [6,5,4], [3,2,1]])

a.sum()

45

In [52]:
a.min()

1

In [56]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [57]:
b.max(axis=0)

array([9, 8, 7])